### ISSUE TITLE
HA indicates that the entities are no longer available

### ISSUE THREAD

**Issue by merlinpimpim** [timothyl13241/Invoxia-HA#9]
Hello,

Does this addon still work?
I haven't had any updates for my 2 sensors for several weeks.

HA indicates that the entities are no longer available.
(My 2 trackers are still visible and active in the Invoxia application.)
![image](https://github.com/user-attachments/assets/82c0b238-b85f-41c6-b8e1-ef98ea069844)

I haven't changed anything on my side concerning Invoxia and it worked for months without a problem before this.
What should I do now?

Thank You

**Comment by MagnusErler** [comment]
Works fine here. Anything in the logs? What HA and Invoxia-HA version are you using?

**Comment by merlinpimpim** [comment]
Nothing in the log viewer (is this where you wanted me to look?)

HA Green:
![image](https://github.com/user-attachments/assets/7fa28fef-2fd1-4d60-9091-675ae9cd75ab)

Invoxia-HA:
![image](https://github.com/user-attachments/assets/c92351e5-0a5c-498a-97ea-04827bed0b78)

Entities "not provided":
![image](https://github.com/user-attachments/assets/16db64a2-d94b-4c66-bc99-36cedce571f3)

**Comment by MagnusErler** [comment]
Have you tried reinstalling the integration in HACS?

**Comment by merlinpimpim** [comment]
Yes, I've reinstalled everything and it's working again.
Thanks for the help!

**Comment by merlinpimpim** [comment]
Yes, I've reinstalled everything and it's working again.
Thanks for the help!
